[package]
name = "relay"
version.workspace = true
edition.workspace = true

[[bin]]
name = "relay"
path = "main.rs"

[dependencies]
clap = { workspace = true }
iroh-relay = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
